### ISSUE TITLE
Explain what's different from the original?

### ISSUE THREAD

**Issue by guystreeter** [pixelfed-glitch/pixelfed#7]
I think it would be very helpful if the README for this project had a brief explanation about why it exists, and what is different from the original pixelfed. I came here from search results about running pixelfed in a container, but having looked at this project, I still don't know why I might choose it over the original. Thanks.

**Comment by Murazaki** [comment]
Hi, sorry for the late response. There is several things, but first and foremost, we're trying to maintain a more up to date build system and semantic versioning than upstream.
